#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import random
from datetime import datetime
from time import sleep

import pyperclip

if not os.path.exists('imagens'):
    os.mkdir('imagens')

numero = random.randint(1, 9)
timestamp = datetime.now().strftime('%d%m%H%M%S')
arquivo = f'imagens/{numero}{timestamp}.png'
link = f"![imagem]({arquivo})"
os.system(f'gnome-screenshot -a -f {arquivo}')

pyperclip.copy(link)
