#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
from datetime import datetime

import pyperclip

if not os.path.exists('imagens'):
    os.mkdir('imagens')

timestamp = datetime.now().strftime('%d%m%H%M%S')
arquivo = f'imagens/{timestamp}.png'
link = f"![imagem]({arquivo})\n---"
os.system(f'gnome-screenshot -a -f {arquivo}')

if os.path.exists(arquivo):
    pyperclip.copy(link)
else:
    pyperclip.copy("  ")
