#!/usr/bin/env bash

getopts "m:" comentario

if [[ ! -z $comentario ]]; then
    comentario="-"
fi

git add .
git commit -m "$comentario"
git push origin master
git push heroku master

heroku run python manage.py migrate
heroku run python manage.py flush
