#!/usr/bin/env bash

modo=$1


if [[ -z $modo ]]; then
    echo "utilize um dos seguintes modos: powersave, performance";
    exit 1
fi

sudo cpupower frequency-set -g $modo
if [[ $? -ne 0 ]]; then
    exit 2
fi

sleep 2s

if [[ $1 = "powersave" ]]; then
    sudo prime-select intel;
fi

if [[ $1 = "performance" ]]; then
    sudo prime-select nvidia;
fi

sudo reboot
